### ISSUE TITLE
Question about MOSI and MOSEI dataset

### ISSUE THREAD

**Issue by vanntc711** [zeroQiaoba/GCNet#2]
Can you give me information about MOSI and MOSEI dataset used in paper? Since MOSI and MOSEI are provided through the CMU-Multimodal SDK, I wanted to know what the file format of these two datasets will be stored in the emotion_data folder, similar to IEMOCAP.
Looking forward to your reply!

**Comment by zeroQiaoba** [comment]
Thanks very much for your interest in our project. More examples on MOSI and MOSEI are provided in **run.sh**.

**Comment by vanntc711** [comment]
Thank you for your reply!
Right now they are not allowed to share the raw videos due to privacy of Youtube content creators, so it's very difficult to follow the instructions in the your provided code.
Could you provide preprocessed files for all 3 datasets?

**Comment by zeroQiaoba** [comment]
Of course. **We provide pre-extracted multimodal features as follows:**
IEMOCAP: https://drive.google.com/file/d/1Hn82-ZD0CNqXQtImd982YHHi-3gIX2G3/view?usp=share_link  -> ./dataset/IEMOCAP/features
CMUMOSI: https://drive.google.com/file/d/1aJxArYfZsA-uLC0sOwIkjl_0ZWxiyPxj/view?usp=share_link  -> ./dataset/CMUMOSI/features
CMUMOSEI:https://drive.google.com/file/d/1L6oDbtpFW2C4MwL5TQsEflY1WHjtv7L5/view?usp=share_link  -> ./dataset/CMUMOSEI/features

**Comment by vanntc711** [comment]
Thank you for your really support. Could you please turn on link sharing, thank you!

**Comment by vanntc711** [comment]
Could you please turn on the link sharing? Thank you!

**Comment by zeroQiaoba** [comment]
Yes, I have shared the link. Can you download the features right now?

**Comment by vanntc711** [comment]
I have downloaded it, the feature you provided is very compatible with the code so I can immediately reproduce the results (although there is a slight difference).
Thank you very much, keep up the good work!
