### ISSUE TITLE
CMU-MOSI and CMU-MOSEI

### ISSUE THREAD

**Issue by xiyang2002** [zeroQiaoba/GCNet#4]
CMU-MOSI and CMU-MOSEI这两个数据集不是一个人在说话吗 ？ 是对话数据集吗

**Comment by zeroQiaoba** [comment]
是的，这两个是单人的，所以只考虑了时序信息

**Comment by xiyang2002** [comment]
每个batch的样本[seqlen, batch, dim] seqlen是取一个batch的最大值吗   其他短样本是用umask来区分吗

**Comment by zeroQiaoba** [comment]
是的
